extends: 
   - airbnb
   - eslint:recommended
   - plugin:prettier/recommended
   - plugin:react/recommended
env:
   node: true
   browser: true
   es6: true
   jest: true

plugins: 
   - prettier
rules: 
   prettier/prettier: error
   no-console: off
   camelcase: off
   no-underscore-dangle : off
   no-eval : off
   no-unused-vars: off
   import/no-unresolved: off
   import/extensions: off