extends: 
   - "airbnb"
   - eslint:recommended
   - plugin:prettier/recommended
   - plugin:react/recommended
env:
    node: true

plugins: 
   - prettier
rules: 
    prettier/prettier: error
    no-console: off